develop:
  name: kaos155
  memory: 1024
  cpus: 2
  ip: 10.10.0.10
  ansible_inv_path: ansible/inventory/vagrant
  ansible_playbook: ansible/site.yml
  port_forwarding: no
  verbose: no
  node_target: BOE
  node_year: 2001
