- hosts: databases
  roles:
  - mysql
  tasks:
  - name: check if database is provisioned
    shell: mysql -u root -e "select * from bbdd_kaos155.boletin;"
    register: checkdb
    ignore_errors: yes
  - name: provision database
    with_items:
    - "{{ kaos_sqlscripts_path }}"
    shell: "mysql -u root bbdd_kaos155 < {{ item }}"
    when: checkdb|failed

- hosts: appservers
  roles:
  - pm2
  tasks:
  - name: check if xpdf tools is installed
    stat:
      path: /usr/local/bin/pdftohtml
    register: checkxpdf
  - include: "{{ playbook_dir }}/pdf.yml"
    when: not checkxpdf.stat.exists
